<!-- #include file = "internal/array.inc" -->
<!-- #include file = "internal/collector.inc" -->
<!-- #include file = "internal/datetime.inc" -->
<!-- #include file = "internal/keyvaluepair.inc" -->
<!-- #include file = "internal/list.inc" -->
<!-- #include file = "internal/metric.inc" -->

<% ' Initialize this library by including all internal files once, avoiding including files multiple times. %>