name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Specifies the target runtime'
        required: true
        default: win-x64
        type: choice
        options:
          - win-x64
          - win-x86

jobs:
  build:
    runs-on: windows-latest # Must be Windows because of COM
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/template/build
