name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest # Must be Windows because of COM
    strategy:
      matrix:
        runtime: [ 'win-x64', 'win-x86' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/template/build
        with:
          runtime: ${{ matrix.runtime }}

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update CHANGELOG
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        tag: ${{ github.ref_name }}

    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Zip artifacts
      run: |
        zip -r win-x64.zip win-x64/
        zip -r win-x86.zip win-x86/

    - name: Create Release ${{ github.ref_name }}
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.changelog.outputs.changes }}
        files: |
          win-x64.zip
          win-x86.zip

    - name: Commit CHANGELOG.md
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        commit_message: 'docs: Update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
        file_pattern: CHANGELOG.md
